### ISSUE TITLE
Change picture on  Android

### ISSUE THREAD

**Issue by E2w4UmWh** [xdsopl/robot36#1]
I recently downloaded the Android version from google-play. I'm using a tablet, Acer Iconia 710. What I could not find out, is how to change the picture? I'm able to rotate the default picture (colour bars) and I'm able to swich the mode and to send the default picture, but there is now function to change the picture. I also couldn't find any hint at the internet.

Thanks for any hint.

**Comment by xdsopl** [comment]
SSTVEncoder is not my app - it's my wife's: https://github.com/olgamiller/SSTVEncoder
Please contact her about issues with her app.

Ahmet

**Comment by E2w4UmWh** [comment]
Thank you! At the given URL I finally found a solution, how to do it.
