### ISSUE TITLE
Support Android MediaProjection API for capturing audio

### ISSUE THREAD

**Issue by penguin359** [xdsopl/robot36#17]
This would allow Robot36 to directly [capture audio](https://developer.android.com/media/platform/av-capture) from another app running on the phone instead of relying on the microphone and speaker to loopback the audio. In particular, this would be good for SDR apps like SDR Touch and RF Analyzer that can capture FM radio signals and demod them to audio. I currently use these apps regularly to pick up SSTV signals and record them. However, to decode them live (or even from a wav recording made by these apps) requires that the audio be played over a speaker where other external sounds can introduce noise in the picture.

I might take a whack at adding this if I can get some time, but thought I'd record it here for now.

**Comment by xdsopl** [comment]
Cool. Curios how that works. I am used to loop-back audio using PulseAudio with varying success to develop Robot36 in the Android emulator but that definitely sounds intriguing. Can't wait to see it in action!

**Comment by KooperTheTrooper15** [comment]
Oh, really? Not planned? This would've been so useful :(

**Comment by xdsopl** [comment]
@KooperTheTrooper15 Yes, but it would be another thing that needs maintaining, as Google continues to change things in Android
