### ISSUE TITLE
Request: Fullscreen mode for art installation

### ISSUE THREAD

**Issue by xdsopl** [xdsopl/robot36#19]
I am very much enjoying exploring sound-to-image with Robot36; I am also not a ham radio person, but an artist with interests in space race/cold-war era media. 

I have a strange request: Would you be willing to add the ability to hide the top menu area (leaving only the waterfall, amplitude and decoded areas visible)? 

Why? Because I would like to use your software running on an SBC (like an ODROID N2+) in an art installation. Robot36 in auto mode creates really lovely visual patterns when intentional errors are introduced, audio from different images mixed, etc., so it is pretty ideal for the aesthetic I am working on, but I find the menu text and icons (in this context) too distracting. 

While I could construct a custom bezel for a monitor in order to hide the "overscan" (like in the old days of CRT!), a software solution would certainly be more elegant.

I have no expectations and sincerely hope it is not offensive for me to ask.

Best Futures!
-c

_Originally posted by @chadmeby in https://github.com/xdsopl/robot36/issues/12#issuecomment-2203889598_

**Comment by xdsopl** [comment]
I just created the following branch, which disables automatic saving of image, the title and the menu bar:
https://github.com/xdsopl/robot36/tree/art

Can you build and test it yourself or do you need an APK?

The app now looks like this in landscape:

![Screenshot_20240703_095927](https://github.com/xdsopl/robot36/assets/1153394/5093dc88-48e9-4a85-959c-1cfe99bb8034)

And like this in portrait mode:

![Screenshot_20240703_095859](https://github.com/xdsopl/robot36/assets/1153394/a1263c98-8b01-441f-ae6a-2fb201c13696)

**Comment by chadmeby** [comment]
Fantastic! Thank you so much both for your willingness to do this and with the absolute lightning response. I do not have a toolchain to compile from source, so an apk would also be much appreciated.

**Comment by xdsopl** [comment]
Try the attached file. You need to unzip first:

[art1.zip](https://github.com/user-attachments/files/16085484/art1.zip)

**Comment by chadmeby** [comment]
I don't have the Odroid available right now, but this is workinv great on my phone! 

Thank you again for this; I am truly grateful.

**Comment by xdsopl** [comment]
Don't mention it. Have fun.

**Comment by chadmeby** [comment]
Update: I have had this version running of Robot36 for days on an Odroid N2+ with a USB mic. I have a microcontroller driving a sound module to serve up the encoded SSTV audio files. It runs great on this platform under Android 9—and has been completely stable for me. 

New request (but only if it is not too much work!): I have been hooking the Odroid up to a variety of different displays, but I am considering a 21:9 ultrawide monitor (in portrait orientation) for the eventual installation. 

The hitch is that on a 21:9, Robot36 is still rendering at 16:9—but padding the decoding display area on each side with white bars. Would it be a big deal to increase the decoding display area to utilize the additional screen real estate?

**Comment by xdsopl** [comment]
Can you show a screenshot or a simple photo of the screen? The app is trying to keep the aspect ratio for the scope view and if that is not that important, we could set the scaling to fill the screen.

**Comment by chadmeby** [comment]
Thanks! Here is a screenshot at 21:9

![Screenshot_2020-05-12_002239](https://github.com/user-attachments/assets/2e5424e5-4e68-4440-954c-98195ef26838)

The colors seem a little strange, but the geometry is correct.

**Comment by xdsopl** [comment]
I've made the frequency plot taller in portrait mode according to the free room you have. Try this one on for size:
[art2.zip](https://github.com/user-attachments/files/16262916/art2.zip)

**Comment by chadmeby** [comment]
Thank you again! The new release works and looks great here on the 21:9 monitor. I appreciate your time. Now for me to start generating the content! =)
