### ISSUE TITLE
Request:Update PD290 Mode

### ISSUE THREAD

**Issue by idontcfr23Q** [xdsopl/robot36#22]
It will be much more convenient if it is added.

**Comment by xdsopl** [comment]
Convenient to whom? Leaving out PD290 was a design decision. Re-adding will take more of my time, which is inconvenient to me.

**Comment by ZeroWolf233** [comment]
> Convenient to whom? Leaving out PD290 was a design decision. Re-adding will take more of my time, which is inconvenient to me.

at least it convenient me, i really need `PD290` Mode, if you like, maybe i can help you to re-add it and maintain it

**Comment by xdsopl** [comment]
I've added experimental PD290 on Friday. To keep aspect ratio and not to make things worse for the other modes, the preview in the scope is cut to 640 pixels horizontally. The stored image has full 800 x 616 resolution tho.

**Comment by ZeroWolf233** [comment]
> I've added experimental PD290 on Friday. To keep aspect ratio and not to make things worse for the other modes, the preview in the scope is cut to 640 pixels horizontally. The stored image has full 800 x 616 resolution tho.

that's really OK, i can stand it

**Comment by xdsopl** [comment]
It is possible to squeeze the 800 pixels into the 640 pixels of the scope, so at least you would see the whole image but it would look odd. I will look into it some other time.
