### ISSUE TITLE
Automatic isn't working

### ISSUE THREAD

**Issue by KooperTheTrooper15** [xdsopl/robot36#23]
Hi!
###Issue
So I'm not a big sstv nerd and I don't know all the terminology involved, but I do know that most if not all sstv systems start their messages with a little pattern that tells the decoder which system it is.
However, as much as I've tried it to work, no matter how loud or clear the audio is, it won't catch it automatically.

###Steps to replicate
1. I open the app, completely fresh.
2. I send a test card from another device, more specifically, the smpte color bars. In robot36, color.
3. I try to receive it from my phone. The other device isn't altering the audio in any way. It's clear and loud.
4. It doesn't receive it as expected. See results in the picture.
![20240802_115226](https://github.com/user-attachments/assets/cb716651-3a93-4143-b235-40fd43673e24)

Thanks for the time and please fix it.

P.S. Offtopic but if you take feedback I'd like you to know that the app was better before, with the old ui and buttons. The old menu was simpler and the app *did* catch transmissions automatically.

**Comment by xdsopl** [comment]
I can only fix things I can reproduce. Have you tried using an audio cable or lowering the audio volume as much as you can? you should also try to send audio just from one speaker and if you have multiple microphones in your device, use the First or Second channel. Hope that helps.

**Comment by KooperTheTrooper15** [comment]
Sorry for bothering you, after some minutes of tinkering with both devices I finally got it working. Thanks!
