### ISSUE TITLE
Feature request: support for importing audio recordings as images

### ISSUE THREAD

**Issue by iyesin** [xdsopl/robot36#29]
Hey!

Thanks a lot for this amazing project!

One feature I miss is to import and convert existing sstv audio recordings to images.

**Comment by xdsopl** [comment]
Issue #17 was suggesting to use the MediaProjection API to reroute audio from other applications to Robot36. That would certainly eliminate the need to add a lot of functionality for dealing with the playback of audio files, as any external media player could be used.

**Comment by ropucyka** [comment]
Not sure TS talking about this. He want to covert .wav with signal - to image. No player needed for that.

**Comment by xdsopl** [comment]
I get more requests about having a more direct way to stream audio from other apps, e.g. YouTube and TikTok into Robot36 in order to avoid signal degradation. This could be simply fixed by a loopback audio cable but phones nowadays seem to skip the audio jacks, so you would need some external soundcard with a loopback.

**Comment by iyesin** [comment]
Hey @xdsopl and @ropucyka!

My feature request was about a feature that will allow me to convert audio files (wav, mp3, ogg, opus) with recorded SSTV signals to a pictures. If there is such existing solution for android I'll be more than glad to read about it. Alternatively, if you know a command-line solution for this (c, c++, python, …) that I can install/run in Termux I would also very glad to read about it.

**Comment by xdsopl** [comment]
Not that I know of. There is a very old version of a Robot36 command line decoder in the master branch written in C99. It can read from an audio device or a wav file and output the decoded picture to either a PPM file or to an SDL window.

**Comment by iyesin** [comment]
@xdsopl thank you!
