### ISSUE TITLE
Is it possible to run an audio file through this app instead of the device’s audio input?

### ISSUE THREAD

**Issue by fredrikhemsen** [xdsopl/robot36#3]
It would very convenient in some cases. Flac or wav would be nice formats.

**Comment by fredrikhemsen** [comment]
That's a no, then?

**Comment by xdsopl** [comment]
Sorry.
I am working on the next App (OFDM Modem) currently and there are already amazing programs that would process WAV files directly:
MMSSTV for Windows and QSSTV for Linux for example.
If you only need to decode the Robot36 format, you can even use the command line version in the master branch of this repository.
Ahmet

**Comment by fredrikhemsen** [comment]
Thanks!
