### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by fossdd** [xdsopl/robot36#5]
In the LICENSE file is called that you use `CC0 1.0 Universal` in both branches

https://github.com/xdsopl/robot36/blob/c609ba488f7209a0ef94687fa2fd93b4cbe52305/COPYING#L3

In the README file of the master branch it says you use this license

https://github.com/xdsopl/robot36/blob/c609ba488f7209a0ef94687fa2fd93b4cbe52305/README#L4-L5

But on the README file of the android branch, the `Apache-2.0` license is called

https://github.com/xdsopl/robot36/blob/9b06796154762bf80cb21678b4215f964a084ad0/README#L3-L13

**Comment by xdsopl** [comment]
The branches are independently licensed: The Android version is Apache and the old experimental SDL version is CC0.
I should have moved the android branch into a new repository long ago and at this point I think it will only cause more harm than good if I do so.

**Comment by fossdd** [comment]
Yes, that could be. But then consider that the COPYING file of the android branch contains the CC0 1.0 Universal license. Using Apache 2.0 would also allow us to publish the app, great.

**Comment by fossdd** [comment]
Oh, no. I was wrong.
