### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [xdsopl/robot36#7]
You can add Screenshots for F-Droid, too, if you want.
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/
https://gitlab.com/snippets/1895688
That was simply information about what is still possible. You would then only have to enter the
screenshots in fastlane. This is just one way that you can also add screenshots to the app view
if you can. If you added screenshots (then F-Droid is happy) and if you can't add any -> then
you can close the issue because it was only an info. Thank you that your app is available in
fdroid. Very much for your attention.

**Comment by xdsopl** [comment]
I hope someone more familiar with fastlane / F-Droid would contribute that and simply create a PR.

**Comment by fossdd** [comment]
Can you attach here maybe screenshots? So that I can create a PR with these files in the right structure?

**Comment by fossdd** [comment]
Can you attach here maybe screenshots? So that I can create a PR with these files in the right structure?

**Comment by xdsopl** [comment]
I've added some pictures. Does this look good?

**Comment by mondlicht-und-sterne** [comment]
Yes i see some pictures. Thank you.

You can close this issue

**Comment by xdsopl** [comment]
How can I verify it myself? When will the pictures be shown on the F-Droid catalog?

**Comment by mondlicht-und-sterne** [comment]
@xdsopl 

Taking a quick look the fastlane looks fine. F-Droid generates the app listing together with a release so the fastlane shown on F-Droid is updated on a new release. 

So they do have to make a new release first.

**Comment by xdsopl** [comment]
Thank you. There are still some things I need to fix in Robot36 so I will make a new release.

**Comment by xdsopl** [comment]
I think there is something wrong. The update is still not online:
https://f-droid.org/en/packages/xdsopl.robot36/

**Comment by xdsopl** [comment]
Just checked the website and the screenshots as well as the new update are online. Thanks!

**Comment by licaon-kter** [comment]
After the rewrite the Fastlane data is gone? :(

**Comment by xdsopl** [comment]
:(
I've added them with commit: f5eafb55ad8199562c9f9219ab63902055352b3f
Is that alright?

**Comment by licaon-kter** [comment]
Looks fine, it will appear with the next release. :)

**Comment by xdsopl** [comment]
Thank you!

**Comment by xdsopl** [comment]
@licaon-kter the F-Droid page points to the old source branch. Can you change that? The new (default) branch is now v2, So a link to just the repository should suffice: https://github.com/xdsopl/robot36

**Comment by licaon-kter** [comment]
F-Droid points the commit for each build, whatever branch it is in. :)

**Comment by licaon-kter** [comment]
This has been updated.

/close this

**Comment by xdsopl** [comment]
So it will also update the LICENSE? It is 0BSD now.

**Comment by licaon-kter** [comment]
done, https://gitlab.com/fdroid/fdroiddata/-/commit/96053525a8b584a0c41d70059288db2bb5a342b3

we weren't aware of the change :shrug:

**Comment by xdsopl** [comment]
what about this line: ```SourceCode: https://github.com/xdsopl/robot36/tree/android```

**Comment by licaon-kter** [comment]
like I said, look at metadata, commit line: https://gitlab.com/fdroid/fdroiddata/-/blob/96053525a8b584a0c41d70059288db2bb5a342b3/metadata/xdsopl.robot36.yml#L84 -> https://github.com/xdsopl/robot36/commit/a505e5f93707a388cf4872ad3577b1662185c0a2 which is the right branch, yes?

The tree is picked up from https://gitlab.com/fdroid/fdroiddata/-/blob/96053525a8b584a0c41d70059288db2bb5a342b3/metadata/xdsopl.robot36.yml#L10

anyway, updated it: https://gitlab.com/fdroid/fdroiddata/-/commit/90012df1e6340095618b1acc312713ec047fd399

**Comment by xdsopl** [comment]
Thanks! I am only guessing here, but I believe that line is shown on the F-Droid page: https://f-droid.org/en/packages/xdsopl.robot36/

**Comment by licaon-kter** [comment]
Yes, now it's "more correct" :)
