### ISSUE TITLE
Save doesn't work (F-Droid version)

### ISSUE THREAD

**Issue by ulville** [xdsopl/robot36#9]
Autosave creates files in the Pictures folder but they are 0 byte empty files. It doesn't save the image in the files. Save button on top (not sure if it's for that purpose but) seems like nonfunctional. After an image transfer is done it shows a toast notification saying file saved (but it only creates empty files). If I touch the save button to manually save, it doesn't do anything. Only option for me right now is to take a screenshot and crop it afterwards and it's not very user-friendly. 

It felt like it can be a permission issue. I'm on **Android 13**. Maybe something has changed in Android which prevents the app from saving files properly? I have given all the permissions the app asked for and I checked it in my settings but no change.

**Comment by macsleeping** [comment]
I'm having the same problem too. Probably it was the last version of the app or it may really the android version. I'm in Samsung A31 running android 12.

**Comment by ropucyka** [comment]
App downloaded from GP or Apkpure **works fine**.
App downloaded from F-Droid not saving pictures (0 bytes size). Version 1.46.

I think it problem of not Robot36. But needs to be confirmed.

Samsung Galaxy A30, Android v11

**Comment by ulville** [comment]
@ropucyka Yes I forgot to mention that I was using the F-Droid version in my first message.

I hadn't tried Play Store version before I see this comment. Now I installed it through Play Store and it works as expected.

I don't know what's wrong with the F-Droid build but shouldn't be too hard to make it feature compatible with the Play Store version.

**Comment by xdsopl** [comment]
I think the issue was introduced in ```v1.46``` and hopefully fixed with ```v1.47```. Please check the new version after it has rolled out on the beta channel and report back.

**Comment by ulville** [comment]
I've installed v1.47 from F-Droid but this time it doesn't even start decoding. Touching on the play button also doesn't do anything. Also all the menu items are disabled except for Privacy Policy.

I tried uninstalling and installing again. It asked for microphone access in the first run and I accepted but it didn't help.

## Here are the screenshots:

![Screenshot_20230703_134223_Robot36](https://github.com/xdsopl/robot36/assets/50755946/1860e6ea-e482-4276-b327-41e9526452b9)

**Comment by Efenstor** [comment]
> I've installed v1.47 from F-Droid but this time it doesn't even start decoding. Touching on the play button also doesn't do anything. Also all the menu items are disabled except for Privacy Policy.
> 
> I tried uninstalling and installing again. It asked for microphone access in the first run and I accepted but it didn't help.

I double that. The same issue, only with the latest version from F-Droid.

**Comment by xdsopl** [comment]
Thank you for the feedback. I guess you both are on Android 13? The fix should roll out soon in ```v1.48```.

**Comment by Efenstor** [comment]
Yes I am on Android 13. Thank you for the cool app! )

**Comment by xdsopl** [comment]
My pleasure. You should also try our new COFDMTV digital modes for picture transmission:
https://www.youtube.com/watch?v=6QfZHwFadYs

**Comment by ulville** [comment]
> Thank you for the feedback. I guess you both are on Android 13? The fix should roll out soon in `v1.48`.

> Yes I am on Android 13. Thank you for the cool app! )

I'm also on Android 13

**Comment by ulville** [comment]
> My pleasure. You should also try our new COFDMTV digital modes for picture transmission: https://www.youtube.com/watch?v=6QfZHwFadYs

I'd like to try. ~Are those different apps? Where can I get them?~ BTW thanks for the great work! 

OK don't bother I found them https://www.aicodix.de/cofdmtv/

I suppose code for the apps themselves are not open but the underlying code which they based on are, am I right?

**Comment by xdsopl** [comment]
The codes are all available here: https://github.com/aicodix
And the apps here: https://play.google.com/store/apps/developer?id=aicodix+GmbH

**Comment by ulville** [comment]
> The codes are all available here: https://github.com/aicodix And the apps here: https://play.google.com/store/apps/developer?id=aicodix+GmbH

Oh thanks! My bad, should have looked deeper

**Comment by ropucyka** [comment]
> My pleasure. You should also try our new COFDMTV digital modes for picture transmission: https://www.youtube.com/watch?v=6QfZHwFadYs

So please add .apk's to github

**Comment by xdsopl** [comment]
With the new bundle system on the Google Play Store that is no more the way to go. There are no APKs. There was an attempt to register Rattlegram with F-Droid but I don't see any progress. If you want progress, please see if you can help:

https://github.com/aicodix/rattlegram/issues/2

**Comment by ropucyka** [comment]
> With the new bundle system on the Google Play Store that is no more the way to go. There are no APKs. There was an attempt to register Rattlegram with F-Droid but I don't see any progress. If you want progress, please see if you can help:
> 
> [aicodix/rattlegram#2](https://github.com/aicodix/rattlegram/issues/2)

Or i'm stupid, or my english so bad. I am (we, users) asked you to just compile APK file and upload it here, on github, here, ready application file to download and install it offline.

**Comment by ulville** [comment]
I've updated to v1.48 from f droid and it fixed both of the problems. Thanks!
